server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  routes:
    logon-service:
      path: /service-logon/**
      serviceId: service-logon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/